# Generated by Django 4.1 on 2024-10-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
