# Generated by Django 5.1.3 on 2024-12-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_worldborder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
