services:

  nginx:

    image: nginx-image

    ports:

      - "80:80"

    volumes:

      - ./nginx/conf.d:/etc/nginx/conf.d

    depends_on:

      - pgadmin4

      - postgis

      - awm_django_app

 

  pgadmin4:

    image: dpage/pgadmin4

    ports:

      - "20080:80"

    environment:

      PGADMIN_DEFAULT_EMAIL: admin@tudublin.ie

      PGADMIN_DEFAULT_PASSWORD: password

    #volumes:

    #  - my_pgadmin4_data:/var/lib/postgresql/data

 

  postgis:

    image: kartoza/postgis

    ports:

      - 25432:5432

    environment:

      POSTGRES_PASSWORD: docker

      POSTGRES_DB: gis

    #volumes:

    #  - my_first_spatialdb_data:/var/lib/postgresql/data

 

  awm_django_app:

    image: awmproject

    ports:

      - 8001:8001

    #build: .

    command: python manage.py runserver 0.0.0.0:8001

    volumes:

      - .:/app

    depends_on:

      - postgis