# Generated by Django 5.1.3 on 2024-12-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_alter_restaurant_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant", name="rating", field=models.FloatField(default=0),
        ),
    ]
